# Krok 1: Używamy oficjalnego obrazu Pythona
FROM python:3.11-slim

# Krok 2: Ustawiamy katalog roboczy
WORKDIR /app

# Krok 3: Kopiujemy zależności i instalujemy je
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

CMD ["python", "flask_main.py"]