# Dockerfile.streamlit
FROM python:3.11-slim
WORKDIR /app
# Użyj specyficznych zależności dla Streamlit
RUN pip install streamlit
COPY streamlit_app.py .
# Uruchom Streamlit na porcie 8080
ENV PORT 8080
CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8080", "--server.address", "0.0.0.0"]